xcopy %0\..\VisualLearningAssistant\bin\Debug\VisualLearningAssistant.exe %0\..\Distribution\Debug\
xcopy %0\..\Frameworks\VLAControlLib\bin\Debug\VLAControlLib.dll %0\..\Distribution\Debug\
xcopy %0\..\Frameworks\VLAPluginLib\bin\Debug\VLAPluginLib.dll %0\..\Distribution\Debug\
xcopy %0\..\VisualLearningAssistant\bin\Debug\Language-Pack\LocalizationDictionary.de-DE.xaml %0\..\Distribution\Debug\Language-Pack\
xcopy %0\..\VisualLearningAssistant\bin\Debug\Language-Pack\LocalizationDictionary.en-IE.xaml %0\..\Distribution\Debug\Language-Pack\
xcopy %0\..\VisualLearningAssistant\bin\Debug\Language-Pack\LocalizationDictionary.es-ES.xaml %0\..\Distribution\Debug\Language-Pack\
xcopy %0\..\VisualLearningAssistant\bin\Debug\Language-Pack\LocalizationDictionary.zh-CN.xaml %0\..\Distribution\Debug\Language-Pack\
xcopy %0\..\Extensions\VLASaveLog\bin\Debug\VLASaveLog.dll %0\..\Distribution\Debug\Plug-in\
xcopy %0\..\Plug-ins\VLAArrays\bin\Debug\VLAArrays.dll %0\..\Distribution\Debug\Plug-in\
xcopy %0\..\Plug-ins\VLALinkedList\bin\Debug\VLALinkedList.dll %0\..\Distribution\Debug\Plug-in\
xcopy %0\..\Plug-ins\VLAShortestPath\bin\Debug\VLAShortestPath.dll %0\..\Distribution\Debug\Plug-in\
xcopy %0\..\Plug-ins\VLABinaryTree\bin\Debug\VLABinaryTree.dll %0\..\Distribution\Debug\Plug-in\
xcopy %0\..\Plug-ins\VLAHuffman\bin\Debug\VLAHuffman.dll %0\..\Distribution\Debug\Plug-in\
xcopy %0\..\Plug-ins\VLAGenetics\bin\Debug\VLAGenetics.dll %0\..\Distribution\Debug\Plug-in\